//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagonostics1
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public int Temperature { get; set; }
        public int BloodSugar { get; set; }
        public int BloodPressure { get; set; }
    }
}
