//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hospital_Simulation_DBEntities : DbContext
    {
        public Hospital_Simulation_DBEntities()
            : base("name=Hospital_Simulation_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Appoinment2> Appoinment2 { get; set; }
        public virtual DbSet<Diagonostics1> Diagonostics1 { get; set; }
    }
}
